Repository ad-earth/FE-admin, pull requests merged in 2022-11, with the labels that each got.

#61 Dam
  package.json
  src/components/postProd/editor/Editor.tsx
  src/components/postProd/editor/editor.module.scss
  src/components/postProd/editor/editor.type.ts
  src/components/postProd/imgForm/ImgForm.tsx
  src/components/postProd/imgForm/imgForm.module.scss
  src/components/postProd/imgForm/imgForm.type.ts
  src/components/postProd/optForm/OptForm.tsx
  src/components/postProd/optForm/optForm.module.scss
  src/components/postProd/optForm/optForm.type.ts
  src/components/postProd/postForm/PostForm.tsx
  src/components/postProd/postForm/postForm.module.scss
  src/components/postProd/postForm/postForm.type.ts
  src/components/postProd/postForm/usePostForm.ts
  src/elements/buttons/Buttons.tsx
  src/elements/buttons/_buttons.style.scss
  src/elements/inputs/Inputs.tsx
  src/elements/inputs/inputs.type.ts
  src/pages/Main.tsx
  src/shared/apis/api.ts
  src/shared/utils/s3Config.ts
  src/store/option.ts
  yarn.lock
Labels: task, 상품등록/수정

#63 버그 수정 및 전역 에러처리
  package.json
  src/App.tsx
  src/components/layouts/nav/nav.module.scss
  src/components/main/bizMoney/BizMoney.tsx
  src/components/main/bizMoney/bizMoney.module.scss
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/modal/withdrawalModal/WithdrawalModal.tsx
  src/components/tables/setAdTable/SetAdTable.tsx
  src/components/tables/setProdTable/SetProdTable.tsx
  src/shared/apis/instance.ts
  yarn.lock
Labels: task, 상품관리, 메인, 상품등록/수정

#67 회원가입 코드 추가
  src/components/signUp/SignUpForm.tsx
  src/elements/inputs/Inputs.tsx
  src/elements/inputs/inputs.type.ts
Labels: 회원가입

#73 banner 기능구현
  src/assets/slideBanner1.png
  src/assets/slideBanner2.png
  src/assets/slideBanner3.png
  src/components/banner/mainBanner/MainBanner.tsx
  src/components/banner/mainBanner/mainBanner.module.scss
  src/components/banner/slideBanner/SlideBanner.tsx
  src/components/banner/slideBanner/slideBanner.module.scss
  src/components/layouts/defaultLoginLayout/DefaultLoginLayout.tsx
  src/pages/Main.tsx
Labels: task
