Repository ad-earth/FE-admin, pull requests merged in 2022-10, with the labels that each got.

#21 공통 input elements & 스타일 수정
  src/components/account/findForm/_findForm.style.scss
  src/components/adReport/adContainer/_adContainer.style.scss
  src/components/layouts/defaultLayout/defaultLayout.style.scss
  src/components/layouts/nav/Nav.tsx
  src/components/layouts/nav/nav.style.scss
  src/components/login/loginContainer/LoginContainer.tsx
  src/components/login/loginContainer/_loginContainer.style.scss
  src/components/prodReport/prodContainer/_prodContainer.style.scss
  src/components/setParcel/serviceContainer/_serviceContainer.style.scss
  src/elements/buttons/Buttons.tsx
  src/elements/buttons/_buttons.style.scss
  src/elements/buttons/buttons.type.ts
  src/elements/inputs/Inputs.tsx
  src/elements/inputs/_inputs.style.scss
  src/elements/inputs/inputs.type.ts
Labels: task, attention

#36 10/8 로컬 개발 완료 Closes #10
  src/App.tsx
  src/components/account/accountContainer/AccoutContainer.tsx
  src/components/account/findForm/FindForm.tsx
  src/components/account/findForm/findForm.module.scss
  src/components/account/findFormBox/FindFormBox.tsx
  src/components/account/findFormBox/findFormBox.module.scss
  src/components/account/findIdForm/FindIdForm.tsx
  src/components/account/findIdForm/findIdForm.module.scss
  src/components/account/findIdForm/getId.ts
  src/components/account/findPwdForm/FindPwdForm.tsx
  src/components/account/findPwdForm/findPwdForm.module.scss
  src/components/account/findPwdForm/getPwd.ts
  src/components/account/findPwdForm/putPwd.ts
  src/components/login/loginContainer/LoginContainer.tsx
  src/components/login/loginContainer/loginContainer.module.scss
  src/components/login/loginContainer/postLogin.ts
  src/components/login/loginContainer/useLoginReg.ts
  src/elements/Loading.tsx
  src/elements/buttons/Buttons.tsx
  src/elements/buttons/buttons.type.ts
  src/elements/inputs/Inputs.tsx
  src/elements/inputs/inputs.type.ts
  src/pages/Account.tsx
  src/pages/styles/account.module.scss
  src/shared/apis/api.ts
  src/shared/apis/instance.ts
Labels: task

#38 datePicker 구현
  src/assets/lcon/arrowRight.svg
  src/components/setProd/prodButton/ProdButton.tsx
  src/components/setProd/setProdSection/SetProdSection.tsx
  src/components/setProd/setProdSection/setProdSection.type.ts
  src/components/setProd/setProdSection/useDelProd.ts
  src/components/setProd/setProdSection/useSetProd.ts
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/useSignUpForm.ts
  src/components/tables/setProdTable/SetProdTabel.tsx
  src/components/tables/setProdTable/switch /Switch.tsx
  src/components/tables/setProdTable/switch /switch.style.ts
  src/components/tables/setProdTable/switch /useSwitch.ts
  src/elements/datePicker/DatePicker.tsx
  src/elements/datePicker/datePicker.module.scss
  src/pages/styles/main.module.scss
  src/shared/apis/api.ts
Labels: task

#40 Dam
  src/assets/lcon/down.png
  src/components/postProd/imgForm/ImgForm.tsx
  src/components/postProd/imgForm/imgForm.module.scss
  src/components/postProd/postForm/PostForm.tsx
  src/components/postProd/postForm/postForm.module.scss
  src/components/postProd/postForm/postForm.type.ts
  src/components/postProd/postForm/usePostForm.ts
  src/elements/dropdown/DropDown.tsx
  src/elements/dropdown/dropdown.module.scss
  src/elements/dropdown/dropdown.type.ts
  src/pages/PostProd.tsx
  src/pages/styles/postProd.module.scss
Labels: task

#42 10/21 로그인 & 계정찾기 & 상품보고서 개발 Resolves #7, #10, #18, #20
  src/App.tsx
  src/components/account/findIdForm/FindIdForm.tsx
  src/components/account/findIdForm/getId.ts
  src/components/account/findIdForm/useFindIdQuery.ts
  src/components/account/findPwdForm/FindPwdForm.tsx
  src/components/account/findPwdForm/getPwd.ts
  src/components/account/findPwdForm/putPwd.ts
  src/components/account/findPwdForm/useFindPwdQuery.ts
  src/components/account/findPwdForm/useResetPwdQuery.ts
  src/components/layouts/nav/Nav.tsx
  src/components/login/loginContainer/LoginContainer.tsx
  src/components/login/loginContainer/loginContainer.module.scss
  src/components/login/loginContainer/postLogin.ts
  src/components/login/loginContainer/useLoginReg.ts
  src/components/prodReport/prodContainer/ProdContainer.tsx
  src/components/prodReport/prodContainer/prodContainer.module.scss
  src/components/prodReport/prodContainer/useDate.ts
  src/components/prodReport/prodContainer/useSalesQuery.ts
  src/components/prodReport/prodFilter/ProdFilter.tsx
  src/components/prodReport/prodFilter/prodFilter.module.scss
  src/components/prodReport/prodFilter/prodFilter.type.ts
  src/components/prodReport/prodFilter/useCategory.ts
  src/components/tables/prodReportTable/ProdReportTable.tsx
  src/components/tables/prodReportTable/prodReportTable.module.scss
  src/components/tables/prodReportTable/prodReportTable.type.ts
  src/elements/datePicker/DatePicker.tsx
  src/elements/datePicker/datePicker.type.ts
  src/elements/inputs/Inputs.tsx
  src/elements/inputs/inputs.type.ts
  src/pages/Login.tsx
  src/pages/ProdReport.tsx
  src/pages/styles/login.module.scss
  src/pages/styles/prodReport.module.scss
Labels: task

#47 10/22 광고페이지 데이터 변경 & 드롭다운 사이즈 변경
  src/components/adReport/adContainer/AdContainer.tsx
  src/components/adReport/adFilter/AdFilter.tsx
  src/components/adReport/adFilter/useProductQuery.ts
  src/elements/dropdown/DropDown.tsx
  src/elements/dropdown/dropdown.module.scss
Labels: task

#53 광고 모달 버그 수정
  src/components/modal/postAdModal/PostAdModal.tsx
Labels: 광고등록/관리

#59 버그 수정 및 enter event 추가
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/signUp/SignUpForm.tsx
  src/components/tables/postAdTable/PostAdTable.tsx
  src/components/tables/postAdTable/postAdTable.module.scss
  src/components/tables/setProdTable/SetProdTable.tsx
  src/components/tables/setProdTable/switch/switch.style.ts
  src/components/tables/setProdTable/switch/useSwitchQuery.ts
  src/elements/inputs/Inputs.tsx
  src/store/prodAd.ts
Labels: bug, task
